generator:

#全局配置
  application:
    outputDir: D:\My-Java-Project\BSC总成MES\BSC-MES\bsc-service\production-management\src\main\java
    author: ganlong
    open: false
    fileOverride: false
    serviceName: %sService
    idType: 1
    dateType: MYSQL
    swagger2: false

#包配置
  package:
    name:
      modelName: production-management
      parent: com.github.ganlong
      controller: controller
      service: service
      serviceImpl: impl
      mapper: mapper
      xml: xml
      entity: entity

#策略配置
  strategy:
    superEntityClass: com.github.ganlong.model.base.BaseEntity
    entityLombokModel: true
    restControllerStyle: true
    superEntityColumns: id
    include: order
    tablePrefix: production_

