#服务端口
server:
  port: 8801

#服务名
spring:
  application:
    name: bsc-production-management
    #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


  #json的全局时间各种
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #环境配置：dev test prod
  profiles:
    active: dev

  #MySQL数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bsc_production?uesSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #MP全局配置
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


