#服务端口
server:
  port: 8802

#服务名
spring:
  application:
    name: material-management

  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  #MySQL数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bsc_material?uesSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"

  #json的全局时间各种
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #环境配置：dev test prod
  profiles:
    active: dev




mybatis-plus:
  configuration:
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

