server:
  port: 9527


spring:
  application:
    name: cloud-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:9572"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: production-management
          uri: lb://production-management
          predicates:
            - RequestBody=true
            - Path=/production-management/**
          filters:
            - StripPrefix=2

        - id: material-mangement
          uri: lb://material-mangement
          predicates:
            - RequestBody=true
            - Path=/material-mangement/**
          filters:
            - StripPrefix=2





